import type { AdaptationCard, ConceptCard, CreatureCard, Diet, EventCard, Period } from "./game-data";

const STATUS = "Locked" as const;

type DeckTwoCreature = {
  key: string;
  name: string;
  scientificName: string;
  printedLevel: 0 | 1 | 2 | 3 | 4;
  diet: Diet;
  period: Period;
  periodColor: string;
  gameplayTaxon: string;
  taxa: string[];
  tags: string[];
  visualTags: string[];
  role: string;
  flavorText: string;
  cardFace?: string;
};

const creature = (entry: DeckTwoCreature): CreatureCard => ({
  kind: "creature",
  status: STATUS,
  ...entry,
});

export const DECK_2_UNIQUE_CREATURES: CreatureCard[] = [
  creature({
    key: "yinlong",
    name: "Yinlong",
    scientificName: "Yinlong downsi",
    printedLevel: 0,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ceratopsian"],
    tags: ["Transitional"],
    visualTags: ["Beaked", "Bipedal"],
    role: "Earliest-ceratopsian bridge and Jurassic Level 0 setup card whose Transitional route crosses Deck 2's concentrated Cretaceous curve.",
    flavorText: "Small and lightly built, Yinlong preserves an early stage of ceratopsian evolution before the elaborate frills and horns of its much later relatives appeared.",
  }),
  creature({
    key: "protoceratops",
    name: "Protoceratops",
    scientificName: "Protoceratops andrewsi",
    printedLevel: 0,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ceratopsian", "Protoceratopsid"],
    tags: ["Herd", "Retaliation"],
    visualTags: ["Frill", "Beaked", "Quadrupedal"],
    role: "Active Herd starter whose Retaliation creates an intentionally unusual Rapid Speciation route into Stegosaurus.",
    flavorText: "Protoceratops lacked the enormous horns of later ceratopsids, but its deep beak and expanding neck frill made it a distinctive and well-protected desert herbivore.",
  }),
  creature({
    key: "ankylosaurus",
    name: "Ankylosaurus",
    scientificName: "Ankylosaurus magniventris",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Thyreophoran", "Ankylosaurid"],
    tags: ["Osteoderm", "Armament"],
    visualTags: ["Armored", "Tail Club", "Beaked", "Quadrupedal"],
    role: "Durable Level 1 bridge whose broad Cretaceous and Archosaur profile deliberately opens several Level 2 routes.",
    flavorText: "Ankylosaurus combined a broad armored body with an enlarged bony tail club, giving a large predator a serious reason to approach its hindquarters cautiously.",
  }),
  creature({
    key: "kentrosaurus",
    name: "Kentrosaurus",
    scientificName: "Kentrosaurus aethiopicus",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Thyreophoran", "Stegosaur", "Stegosaurid"],
    tags: ["Territorial", "Saboteur", "Armament"],
    visualTags: ["Plated", "Tail Spikes", "Beaked", "Quadrupedal"],
    role: "Disruptive stegosaur bridge that converts weaponized rear anatomy into lane pressure without duplicating Stegosaurus's Retaliation identity.",
    flavorText: "Kentrosaurus carried plates over the front of its back and long paired spikes toward the hips and tail, concentrating its protection into a dangerous rear defense.",
  }),
  creature({
    key: "pachycephalosaurus",
    name: "Pachycephalosaurus",
    scientificName: "Pachycephalosaurus wyomingensis",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Pachycephalosaurid"],
    tags: ["Cranial Display", "Specialized", "Rivalry"],
    visualTags: ["Cranial Dome", "Bipedal"],
    role: "Facing-Niche duel specialist whose Specialized Rivalry provides +2 Battle Level without changing Rivalry's lane condition.",
    flavorText: "Its greatly thickened skull roof was surrounded by knobs and spikes; whether used in direct impact, flank-butting, display, or several behaviors remains debated.",
  }),
  creature({
    key: "plateosaurus",
    name: "Plateosaurus",
    scientificName: "Plateosaurus trossingensis",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Triassic",
    periodColor: "Slate Gray",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Plateosaurid"],
    tags: ["Transitional", "Armament"],
    visualTags: ["Long Neck", "Grasping Hands", "Bipedal"],
    role: "Deck 2's only Triassic Creature and a major Period bridge, with Armament representing its enlarged thumb claw and robust defensive anatomy.",
    flavorText: "Plateosaurus combined a long neck and deep torso with grasping hands and a large thumb claw, preserving an early sauropodomorph body plan before the rise of fully graviportal giants.",
  }),
  creature({
    key: "mussaurus",
    name: "Mussaurus",
    scientificName: "Mussaurus patagonicus",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph"],
    tags: ["Herd", "Nesting"],
    visualTags: ["Long Neck", "Quadrupedal", "Bipedal"],
    role: "Nursery development engine: Herd resolves first, then Nesting may place an adjacent Level 0 and end the turn after its entry effects.",
    flavorText: "Eggs, juveniles, and adults preserved together indicate that Mussaurus nested colonially and remained in age-structured groups, unusually strong evidence of social behavior in an early sauropodomorph.",
  }),
  creature({
    key: "giant-moa",
    name: "Giant Moa",
    scientificName: "Dinornis robustus",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Quaternary",
    periodColor: "Ice White",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Theropod", "Avialan", "Bird", "Palaeognath", "Dinornithiform"],
    tags: ["Gigantic", "Generalist"],
    visualTags: ["Flightless", "Long Legs", "Feathered"],
    role: "Large, flexible Quaternary bridge that counts as Saurischian for Air Sacs but deliberately does not receive Graviportal.",
    flavorText: "Giant moa were towering, flightless browsing birds of New Zealand. Their extraordinary height made them immense among birds without producing the heavy, graviportal limb construction of giant terrestrial quadrupeds.",
  }),
  creature({
    key: "styracosaurus",
    name: "Styracosaurus",
    scientificName: "Styracosaurus albertensis",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ceratopsian", "Ceratopsid", "Centrosaurine"],
    tags: ["Herd", "Cranial Display"],
    visualTags: ["Horns", "Frill", "Beaked", "Quadrupedal"],
    role: "Low-level ceratopsian Herd bridge that develops the group and display branches without duplicating their defensive endpoints.",
    flavorText: "Bonebeds indicate that Styracosaurus sometimes gathered in groups, while long spikes projected from its neck frill to create one of the most conspicuous cranial displays among ceratopsians.",
  }),
  creature({
    key: "amargasaurus",
    name: "Amargasaurus",
    scientificName: "Amargasaurus cazaui",
    printedLevel: 1,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod", "Dicraeosaurid"],
    tags: ["Spinal Sail", "Graviportal"],
    visualTags: ["Elongated Neural Spines", "Long Neck", "Quadrupedal"],
    role: "Distinct saurischian Level 1 bridge whose Spinal Sail adds cross-deck texture while Graviportal supports sauropod progression.",
    flavorText: "Amargasaurus carried paired rows of greatly elongated neural spines along its neck and back. Their exact soft-tissue covering remains debated, but the structure gave this compact sauropod an unmistakable profile.",
    cardFace: "/card-faces/amargasaurus.png",
  }),
  creature({
    key: "parasaurolophus",
    name: "Parasaurolophus",
    scientificName: "Parasaurolophus walkeri",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ornithopod", "Hadrosaurid", "Lambeosaurine"],
    tags: ["Herd", "Cranial Display", "Resonance"],
    visualTags: ["Cranial Crest", "Beaked", "Duck-billed"],
    role: "Mid-curve Herd value card and display-focused hadrosaur; Resonance is retained as a mechanically empty identity Tag.",
    flavorText: "Its long, hollow crest connected to the nasal passages and could shape resonant calls, giving Parasaurolophus a striking structure suited to visual and acoustic communication.",
  }),
  creature({
    key: "stegosaurus",
    name: "Stegosaurus",
    scientificName: "Stegosaurus stenops",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Thyreophoran", "Stegosaur", "Stegosaurid"],
    tags: ["Armament", "Retaliation"],
    visualTags: ["Plated", "Tail Spikes", "Beaked", "Quadrupedal"],
    role: "Reactive defensive lane anchor, deliberate Thagomizer endpoint, and unusual Rapid Speciation destination from Protoceratops.",
    flavorText: "Stegosaurus carried two staggered rows of tall plates and four long tail spikes. Fossil injuries support the tail's use as a defensive weapon capable of inflicting serious wounds on predators.",
  }),
  creature({
    key: "therizinosaurus",
    name: "Therizinosaurus",
    scientificName: "Therizinosaurus cheloniformis",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Theropod", "Maniraptoran", "Therizinosaurid"],
    tags: ["Specialized", "Deimatic"],
    visualTags: ["Feathered", "Large Claws", "Bipedal"],
    role: "Sticky technical Level 2 whose Specialized Deimatic protection lasts through two opposing turns.",
    flavorText: "Therizinosaurus combined an herbivorous theropod body plan with immense manual claws. Their exact use remains uncertain, but their scale alone created a formidable deterrent and display structure.",
  }),
  creature({
    key: "iguanodon",
    name: "Iguanodon",
    scientificName: "Iguanodon bernissartensis",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ornithopod", "Iguanodontian"],
    tags: ["Armament", "Resourceful"],
    visualTags: ["Beaked", "Thumb Spike", "Robust Hands"],
    role: "Flexible technical Level 2 whose thumb spike supplies Armament while its differentiated hands and locomotion support Resourceful.",
    flavorText: "Iguanodon had an unusually specialized hand: a stout thumb spike, weight-bearing central fingers, and a flexible outer digit combined defense, locomotion, and manipulation in one structure.",
  }),
  creature({
    key: "pachyrhinosaurus",
    name: "Pachyrhinosaurus",
    scientificName: "Pachyrhinosaurus canadensis",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ceratopsian", "Ceratopsid", "Centrosaurine"],
    tags: ["Herd", "Cranial Display", "Rivalry"],
    visualTags: ["Nasal Boss", "Frill", "Beaked", "Quadrupedal"],
    role: "Ceratopsian progression hub whose nasal boss and bonebed record support Herd, display, and cautious Rivalry interpretations.",
    flavorText: "Mass-death assemblages preserve many Pachyrhinosaurus together, while its skull replaced a long nasal horn with a massive roughened boss suited to display and forceful intraspecific contact.",
  }),
  creature({
    key: "shunosaurus",
    name: "Shunosaurus",
    scientificName: "Shunosaurus lii",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod"],
    tags: ["Armament", "Graviportal"],
    visualTags: ["Tail Club", "Long Neck", "Quadrupedal"],
    role: "Weaponized sauropod Level 2 whose terminal tail club supplies Armament while its weight-bearing build supplies Graviportal.",
    flavorText: "Shunosaurus is known from unusually complete skeletons and carried a compact bony club at the end of its tail, adding a specialized defensive weapon to an early sauropod body plan.",
  }),
  creature({
    key: "saltasaurus",
    name: "Saltasaurus",
    scientificName: "Saltasaurus loricatus",
    printedLevel: 2,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod", "Titanosaur", "Saltasaurid"],
    tags: ["Osteoderm", "Graviportal"],
    visualTags: ["Osteoderms", "Long Neck", "Quadrupedal"],
    role: "Armored sauropod Level 2 and one of Deck 2's cleanest Air Sacs launchpads into Dreadnoughtus.",
    flavorText: "Saltasaurus combined a graviportal titanosaur frame with bony osteoderms embedded in its skin, demonstrating that substantial dermal armor evolved even among giant sauropods.",
  }),
  creature({
    key: "shantungosaurus",
    name: "Shantungosaurus",
    scientificName: "Shantungosaurus giganteus",
    printedLevel: 3,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ornithopod", "Hadrosaurid"],
    tags: ["Gigantic", "Herd"],
    visualTags: [],
    role: "High-end Herd endpoint that combines enormous hadrosaur size with Deck 2's horizontal development engine.",
    flavorText: "Shantungosaurus was among the largest known hadrosaurids, combining a deep duck-billed skull with a body that rivaled the length of many giant theropods.",
  }),
  creature({
    key: "brachiosaurus",
    name: "Brachiosaurus",
    scientificName: "Brachiosaurus altithorax",
    printedLevel: 3,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod", "Brachiosaurid"],
    tags: ["Gigantic", "Graviportal", "Overreach"],
    visualTags: ["Long Neck", "Quadrupedal"],
    role: "High-browsing sauropod finisher whose group-relative feeding reach queues an additional draw next turn.",
    flavorText: "Brachiosaurus had forelimbs longer than its hind limbs, lifting the shoulders and long neck into a high browsing profile unlike that of many other sauropods.",
  }),
  creature({
    key: "triceratops",
    name: "Triceratops",
    scientificName: "Triceratops horridus",
    printedLevel: 3,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Ornithischian", "Ceratopsian", "Ceratopsid"],
    tags: ["Gigantic", "Cranial Display", "Bastion"],
    visualTags: ["Horns", "Frill", "Beaked", "Quadrupedal"],
    role: "Defensive boss and active barrier piece whose Bastion protects adjacent low-Level Creatures.",
    flavorText: "A massive skull carried two long brow horns, a shorter nasal horn, and a broad solid frill, forming one of the most imposing defensive displays among dinosaurs.",
  }),
  creature({
    key: "mamenchisaurus",
    name: "Mamenchisaurus",
    scientificName: "Mamenchisaurus hochuanensis",
    printedLevel: 3,
    diet: "Herbivore",
    period: "Jurassic",
    periodColor: "Logo Red",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod", "Mamenchisaurid"],
    tags: ["Graviportal", "Specialized", "Overreach"],
    visualTags: ["Extremely Long Neck", "Quadrupedal"],
    role: "Alternative Jurassic Level 3 endpoint that trades Gigantic for two delayed draws through Specialized Overreach.",
    flavorText: "Mamenchisaurus devoted an exceptional proportion of its body length to the neck, producing an extreme feeding envelope even when compared with other long-necked sauropods.",
  }),
  creature({
    key: "dreadnoughtus",
    name: "Dreadnoughtus",
    scientificName: "Dreadnoughtus schrani",
    printedLevel: 4,
    diet: "Herbivore",
    period: "Cretaceous",
    periodColor: "Lime Green",
    gameplayTaxon: "Archosaur",
    taxa: ["Vertebrate", "Amniote", "Archosaur", "Dinosaur", "Saurischian", "Sauropodomorph", "Sauropod", "Titanosaur"],
    tags: ["Sovereign", "Graviportal"],
    visualTags: ["Long Neck", "Massive-bodied", "Quadrupedal"],
    role: "Exceptional terrestrial Level 4 monument. Sovereign supplies Gigantic and protects the Victory Level of this Herbivore branch.",
    flavorText: "Dreadnoughtus is represented by one of the more complete skeletons known for a giant titanosaur. Its holotype was still growing, underscoring the extraordinary scale its lineage could attain.",
  }),
];

export const DECK_2_UNIQUE_KEYS = new Set(DECK_2_UNIQUE_CREATURES.map((card) => card.key));

export const DECK_2_INHERITED_SUPPORT_KEYS = [
  "cryptic-camouflage",
  "biogenesis",
  "rapid-speciation",
  "natural-selection",
  "dig-site-excavation",
  "abiogenesis",
  "obligate-migration",
  "genetic-drift",
  "wildfire",
  "drought",
  "geological-boundary",
] as const;

export const DECK_2_NEW_SUPPORTS: Array<AdaptationCard | ConceptCard | EventCard> = [
  {
    key: "air-sacs",
    kind: "adaptation",
    name: "Air Sacs",
    eligibility: "saurischian",
    rules: "Attach only to a Saurischian Creature. When you override the attached Creature with another Saurischian Creature, if either Creature has Gigantic, the overriding Creature may be exactly 2 Printed Levels higher. All normal override-match requirements still apply.",
    note: "Birds count as Saurischian. Air Sacs changes only the allowed Level jump and never supplies an override category.",
    status: STATUS,
  },
  {
    key: "thagomizer",
    kind: "adaptation",
    name: "Thagomizer",
    eligibility: "herbivore-armament-retaliation",
    rules: "Attach only to an Herbivore with Armament or Retaliation. It gets +1 Battle Level while defending. If it has both Tags, it destroys the attacking Creature on successful defenses, including ties. If it is a Stegosaur, it also contributes +1 Victory Level.",
    note: "Stampede inverts defensive Tag effects only; this defensive Adaptation never becomes an attacking bonus.",
    status: STATUS,
  },
  {
    key: "dental-battery",
    kind: "adaptation",
    name: "Dental Battery",
    eligibility: "ornithischian",
    rules: "Attach only to an Ornithischian Creature. When you override the attached Creature with another Ornithischian Creature, attach this Adaptation to the new Creature instead of sending it to your History Pile, then draw 1 card. When this card is sent to your History Pile for any reason, draw 1 card.",
    note: "Its transfer is the explicit exception to the general rule that an attached Adaptation leaves with its Creature.",
    status: STATUS,
  },
  {
    key: "facultative-quadrupedality",
    kind: "adaptation",
    name: "Facultative Quadrupedality",
    eligibility: "any",
    rules: "Once per turn during your Development Phase, you may move the attached Creature to an empty adjacent friendly Niche. This movement does not trigger effects that activate when a Creature enters a Niche.",
    note: "The Adaptation moves with its Creature. Graviportal and other movement restrictions still apply.",
    status: STATUS,
  },
  {
    key: "genetic-mutations",
    kind: "concept",
    name: "Genetic Mutations",
    rules: "Add a random Adaptation card from your deck to your hand. Then shuffle your deck.",
    note: "The selection is made only from Adaptations currently remaining in your deck. If none remain, add nothing.",
    status: STATUS,
  },
  {
    key: "stampede",
    kind: "event",
    eventType: "instant",
    name: "Stampede",
    rules: "Starting with your leftmost Creature and proceeding counter-clockwise around the board, each Herbivore Hunts the Creature in its opposing Niche, if able. Resolve each Hunt before proceeding to the next Creature. If an eligible Creature leaves play before its Hunt, skip it. These Hunts ignore Diet, and Herbivores that entered play this turn may Hunt. During these Hunts, effects of Tags that apply while their Creature is defending also apply while that Creature is attacking. Any survival clause attached to such an effect applies to the opposing Creature instead. This does not apply to Adaptations or effects governing Hunt eligibility. After this effect resolves, end your turn without entering your Battle Phase.",
    note: "All Herbivores on both sides participate. Shell, Osteoderm, Dermal Armor, Retaliation, Bastion, and the Cold-added Gigantic defense effect invert; targeting and Hunt-permission effects do not.",
    status: STATUS,
  },
];
